dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

dataset:
    train:
        type: NeRF
        scene_name: lego
        skip: 4
        img_scale: 1.0
        scale_radius: 3.0
        precache: False

model:
    rays:
        #bounding_radius: 3.0
        volume:
            n_grid: None
            origin: [0.0, -0.11, 0.0]
            xyz_len: [1.2, 1.2, 2.0]
#        near: 1.5
#        far: 4.5

inference:
    render:
        type: [spiral]
        n_cam: [20]
        radius: 3.0
        u_start: 0.5
        v_range: [-0.6, -0.2]

    volume:
        n_grid: 4       # just for visual purpose
        origin: [0.0, -0.11, 0.0]
        xyz_len: [1.2, 1.2, 2.0]
