name: dtu_65_nerf_ngp

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/benchmark/DTU/nerf_ngp'
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/dtu_65_nerf_ngp'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/benchmark/DTU/nerf_ngp/dtu_65_nerf_ngp/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 4096
worker: 4

optim:
    ema:
        decay: 0.95
    lr: 1e-2
    optim_type: adam
    weight_decay: 1e-6
    eps: 1e-15
    lr_scheduler:
        type: MultiStepLR
        lr_gamma: 0.33
        lr_steps: [20000, 30000, 40000, 50000]

    clip_gradients: 0.0
    clip_warmup: -1
    clip_gradients_warmup: 0.0

progress:
    start_epoch: -1
    epoch: 50000
    save_time: 1800

    epoch_loss: 100
    iter_loss: 1
    save_progress: False
    epoch_save_progress: 5000
    iter_save_progress: 1

    epoch_save_checkpoint: 10000
    local_progress: False

    epoch_val: 5000
    save_progress_val: False
    max_samples_val: 1

    init_eval: False
    epoch_eval: 10000
    max_samples_eval: 25

dataset:
    train:
        type: DTU
        scan_id: 65
        img_scale: 1.0
        center_pixel: True
        scale_radius: 3.0
        align_cam: True
        precache: True
        device: gpu
        scheduler:
            precrop: # precrop
                ratio: 0.5
                max_epoch: 500
            bkg_color:
                color: random
            dynamic_batch_size:
                update_epoch: 16

    eval:
        eval_batch_size: 1
        type: DTU
        scan_id: 65
        img_scale: 1.0
        center_pixel: True
        scale_radius: 3.0
        align_cam: True
        precache: True
        device: gpu
        augmentation:
            blend_bkg_color:            # eval on white bkg
                bkg_color: [1.0, 1.0, 1.0]

model:
    type: NeRF
    obj_bound:
        volume:
            n_grid: 128
            side: 1.5
        epoch_optim: 16
        epoch_optim_warmup: 256
        ray_sample_acc: True
        ray_sample_fix_step: True
        near_distance: 0.2
        opa_thres: 0.01
        bkg_color: [1.0, 1.0, 1.0]  # If want black-background, set [0.0, 0.0, 0.0]
        log_max_allowance: 18  # only used for dynamic batch_size, 1 << 18 = 4096*64
    rays:
        n_sample: 1024
        inverse_linear: False
        perturb: True
        add_inf_z: False
        noise_std: 0.0
        white_bkg: True  # for eval only, if want black-background, set [0.0, 0.0, 0.0]
    chunk_rays: 32768   # 4096 * 16
    chunk_pts: 1048576  # 4096 * 256
    geometry:
        type: FusedMLPGeoNet
        W: 64
        D: 1
        skips: []
        encoder:
            type: HashGridEmbedder
            input_dim: 3
            n_freqs: 0  # do not do geo init
            side: 1.5
            n_levels: 16
            n_feat_per_entry: 2
            hashmap_size: 19
            base_res: 16
            max_res: 2048
            include_input: False
            backend: tcnn
        W_feat: 16
        geometric_init: False
        out_act_cfg:
            type: TruncExp
    radiance:
        type: FusedMLPRadianceNet
        mode: 'fv'   # This order matter push up ~0.5 PSNR on eval
        W: 64
        D: 2
        encoder:
            view:
                type: SHEmbedder
                input_dim: 3
                n_freqs: 4
                include_input: False
                backend: tcnn
        W_feat_in: 16

loss:
    ImgLoss:
        keys: ['rgb_coarse']
        loss_type: Huber
        delta: 0.1
        weight: 5

metric:
    PSNR:

train_metric:
    PSNR:
        key: 'rgb_coarse'
