name: capture_qqtiger_nerf

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/capture_qqtiger_nerf'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/capture_qqtiger_nerf/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 4096
worker: 4

optim:
    lr: 5e-4
    optim_type: adam
    weight_decay: 0.0
    lr_scheduler:
        type: ExponentialLR
        lr_gamma: 0.1
        lr_steps: [200000]

    clip_gradients: 0.0
    clip_warmup: -1
    clip_gradients_warmup: 0.0

progress:
    start_epoch: -1
    epoch: 300000
    save_time: 1800

    epoch_loss: 10
    iter_loss: 1
    save_progress: False
    epoch_save_progress: 10
    iter_save_progress: 10

    epoch_val: 10000
    save_progress_val: True
    max_samples_val: 1

    epoch_save_checkpoint: 100000
    local_progress: False

    init_eval: False
    epoch_eval: 100000
    max_samples_eval: 3

dataset:
    train:
        type: Capture
        scene_name: qqtiger
        img_scale: 1.0
        scale_radius: 3.0
        pc_radius: 2.0
        precache: True
        augmentation:
            shuffle: True

    val:
        type: Capture
        scene_name: qqtiger
        img_scale: 0.5
        scale_radius: 3.0
        pc_radius: 2.0
        precache: False

    eval:
        eval_batch_size: 1
        eval_max_sample: 3
        type: Capture
        scene_name: qqtiger
        img_scale: 1.0
        scale_radius: 3.0
        pc_radius: 2.0
        precache: True

inference:
    render:
        type: [circle, spiral]
        n_cam: [30, 60]
        radius: 3.0
        u_start: 0.75
        v_ratio: -0.2
        v_range: [-0.5, 0]
        n_rot: 3
        fps: 5

    volume:
        n_grid: 512
        side: 1.5
        level: 50.0

model:
    type: NeRF
    rays:
        bounding_radius: 3.0
        far: 8.0
        n_sample: 64
        n_importance: 128
        inverse_linear: False
        perturb: True
        add_inf_z: True
        noise_std: 1.0
    chunk_rays: 32768
    chunk_pts: 131072
    geometry:
        W: 256
        D: 8
        skips: [4]
        input_ch: 3
        embed_freq: 10
        W_feat: 256
        geometric_init: False
    radiance:
        mode: 'vf'
        W: 128
        D: 1
        input_ch_view: 3
        embed_freq_view: 4
        W_feat_in: 256

loss:
    ImgCFLoss:
        weight: 1.0

metric:
    PSNRFine:
