dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

dataset:
    train:
        type: LLFF
        scene_name: fern
        img_scale: 0.125
        precache: False
        ndc_space: True
        center_pose: False

model:
    rays:
        # Use near far as 0/1 if in ndc_space by default
#        near: 0.0
#        far: 1.0
