dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

dataset:
    train:
        type: MipNeRF360
        scene_name: garden
        skip: 8
        img_scale: 0.25
        # center_by_view_dirs: True  # just for checking
        cam_t_offset: [0.0, 1.8, 0.0]
        scale_radius: 3.0
        precache: False

model:
    rays:
        bounding_radius: 3.0

inference:
    render:
        type: [spiral]
        n_cam: [20]
        radius: 3.0
        u_start: 0.0
        v_range: [-0.6, -0.2]

    volume:
        n_grid: 4       # just for visual purpose
        side: 2.0
