# The hdrnerf model with two pass

model:
    type: HDRNeRF
    rays:
        bounding_radius: 3.0          # bounding ray sampling region
        near: 1.5                     # hardcode near zvals
        far: 8.0                      # hardcode far zvals
        n_sample: 64                  # n_sample for zvals sampling
        n_importance: 128             # n_importance for zvals for hierarchical sampling
        inverse_linear: False         # inverse_linear make zvals close to near
        perturb: True                 # perturb zvals interval
        add_inf_z: True               # Add inf zval for ray marching
        noise_std: 1.0                # noise for sigma in training
        white_bkg: False              # cast the background as white
    chunk_rays: 32768                 # each chunk to process 1024*32(ray), enough for 32 GB
    chunk_pts: 131072                 # each chunk to progress 4096*32(pts), for model forward
    geometry:
        W: 256                        # linear hidden neuron
        D: 8                          # num of linear, not include final
        skips: [4]                    # pos to add input embedding
        encoder:                      # encoder
            type: FreqEmbedder        # type of encoder
            input_dim: 3              # xyz input channel
            n_freqs: 10               # xyz embed freq
        W_feat: 256                   # extra feature output
        geometric_init: False         # whether to use geometric init. need radius_init
    radiance:
        mode: 'vf'                    # view_dir and feature only
        W: 128                        # linear hidden dim
        D: 1                          # num of linear, not include final
        encoder:
            view:
                type: FreqEmbedder    # type of encoder
                input_dim: 3          # view input channel
                n_freqs: 4            # view embed freq
        W_feat_in: 256                # dim for feature from geometry
        out_act_cfg:
            type: identity            # Do not use sigmoid to hdr dynamic value
    exp_mlps:
        W: 128                        # rgb_h -> l internal channel
        D: 1                          # hidden layer depth
