# The nerf model with two pass. Use dense Volume with linear layers.

model:
    type: NeRF
    rays:
        bounding_radius: 3.0          # bounding ray sampling region
        near: 1.5                     # hardcode near zvals
        # far: 4.0                    # should not set far if background model here
        n_sample: 64                  # n_sample for zvals sampling
        n_importance: 128             # n_importance for zvals for hierarchical sampling
        inverse_linear: False         # inverse_linear make zvals close to near
        perturb: True                 # perturb zvals interval
        add_inf_z: False              # rgb mode must be False, sigma mode suggest True
        noise_std: 1.0                # noise for sigma in training
        white_bkg: False              # cast the background as white
    chunk_rays: 32768                 # each chunk to process 1024*32(ray), enough for 32 GB
    chunk_pts: 131072                 # each chunk to progress 4096*32(pts), for model forward
    geometry:
        type: VolGeoNet               # Dense Volume network
        W_vol: 0                      # No geo value since use nn
        W_feat_vol: 256               # feat on voxel grid
        n_grid: 128                   # num of grid
        side: 1.5                     # volume length
        use_nn: True                  # use nn
        W: 256                        # linear hidden dim
        D: 2                          # num of linear, not include final
        include_input: True           # linear layer include input
        encoder:                      # encoder
            type: FreqEmbedder        # type of encoder
            input_dim: 3              # xyz input channel
            n_freqs: 10               # xyz embed freq
        W_feat: 256                   # extra feature output
        geometric_init: False         # whether to use geometric init. need radius_init
    radiance:
        type: VolRadianceNet          # Dense Volume network
        mode: 'vf'                    # view_dir and feature only
        n_grid: 128                   # num of grid
        side: 1.5                     # volume length
        use_nn: True                  # use nn
        W: 128                        # linear hidden dim
        D: 4                          # num of linear, not include final
        encoder:
            view:
                type: FreqEmbedder    # type of encoder
                input_dim: 3          # view input channel
                n_freqs: 4            # view embed freq
        W_feat_in: 256                # dim for feature from geometry
