name: nerf_lego_nerf_ngp

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/nerf_lego_nerf_ngp'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/nerf_lego_nerf_ngp/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 4096
worker: 4

optim:
    lr: 1e-2
    optim_type: adam
    weight_decay: 0.0
    lr_scheduler:
#        type: ExponentialLR
#        lr_gamma: 0.1
#        lr_steps: [15000]
        type: CosineAnnealingLR
        tmax: 15000
        eta_min: 1e-4

    clip_gradients: 0.0
    clip_warmup: -1
    clip_gradients_warmup: 0.0

progress:
    start_epoch: -1
    epoch: 50000
    save_time: 1800

    epoch_loss: 100
    iter_loss: 1
    save_progress: True
    epoch_save_progress: 5000
    iter_save_progress: 1

    epoch_save_checkpoint: 10000
    local_progress: True

    epoch_val: 5000
    save_progress_val: True
    max_samples_val: 1

    init_eval: False
    epoch_eval: 5000
    max_samples_eval: 25

dataset:
    train:
        type: NeRF
        scene_name: lego
        img_scale: 1.0
        scale_radius: 3.0
        precache: True
        device: gpu
        scheduler:
            precrop:
                ratio: 0.5
                max_epoch: 500

    val:
        skip: 8
        type: NeRF
        scene_name: lego
        img_scale: 1.0
        scale_radius: 3.0
        precache: False
        device: gpu

    eval:
        eval_batch_size: 1
        skip: 8
        type: NeRF
        scene_name: lego
        img_scale: 1.0
        scale_radius: 3.0
        precache: False
        device: gpu

inference:
    to_gpu: True
    render:
        type: [spiral]
        n_cam: [60]
        repeat: [1]
        radius: 3.0
        u_start: 0.5
        v_range: [-0.6, -0.2]
        fps: 5

    volume:
        n_grid: 512
        origin: [0.0, -0.11, 0.0]
        xyz_len: [1.2, 1.2, 2.0]
        level: 50.0
        chunk_pts_factor: 32
        render_mesh:
            backend: pytorch3d

model:
    type: NeRF
    obj_bound:
        volume:
            n_grid: 128
            origin: [0.0, -0.11, 0.0]
            xyz_len: [1.2, 1.2, 2.0]
        epoch_optim: 16
        epoch_optim_warmup: 256
    rays:
        n_sample: 1024
        inverse_linear: False
        perturb: True
        add_inf_z: True
        noise_std: 0.0
        white_bkg: True
    chunk_rays: 32768
    chunk_pts: 131072
    geometry:
        W: 64
        D: 1
        skips: []
        encoder:
            type: HashGridEmbedder
            input_dim: 3
            n_freqs: 0  # do not do geo init
            origin: [0.0, -0.11, 0.0]
            xyz_len: [1.2, 1.2, 2.0]
            n_levels: 16
            n_feat_per_entry: 2
            hashmap_size: 19
            base_res: 16
            max_res: 512
            backend: tcnn
        W_feat: 16
        geometric_init: False
    radiance:
        mode: 'vf'
        W: 64
        D: 2
        encoder:
            view:
                type: SHEmbedder
                input_dim: 3
                n_freqs: 4
                backend: tcnn
        W_feat_in: 16

loss:
    ImgLoss:
        keys: ['rgb_coarse']
        weight: 1.0

#    RegMaskLoss:
#        keys: ['mask_coarse']
#        weight: 0.1
#
#    RegWeightsLoss:
#        keys: ['weights']
#        weight: 0.1

metric:
    PSNR:

train_metric:
    PSNR:
        key: 'rgb_coarse'
