name: mipnerf360_garden_neus_nerfpp

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/mipnerf360_garden_neus_nerfpp'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/mipnerf360_garden_neus_nerfpp/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 1024
worker: 4

optim:
    lr: 5e-4
    optim_type: adam
    weight_decay: 0.0
    lr_scheduler:
        type: WarmUpCosineLR        # follow the original implementation
        lr_steps: [5000]
        min_factor: 0.05

    clip_gradients: 0.0
    clip_warmup: -1
    clip_gradients_warmup: 0.0

progress:
    start_epoch: -1
    epoch: 300000
    save_time: 1800

    epoch_loss: 100
    iter_loss: 1
    save_progress: True
    epoch_save_progress: 50000
    iter_save_progress: 1

    epoch_val: 50000
    save_progress_val: True
    max_samples_val: 1

    epoch_save_checkpoint: 100000
    local_progress: False

    init_eval: False
    epoch_eval: 100000
    max_samples_eval: 25

dataset:
    train:
        type: MipNeRF360
        scene_name: garden
        test_holdout: 24
        img_scale: 0.25
        scale_radius: 3.0
        cam_t_offset:  [0.0, 1.4, 0.0]
        device: gpu
        precache: True

    val:
        type: MipNeRF360
        scene_name: garden
        test_holdout: 24
        img_scale: 0.25
        scale_radius: 3.0
        cam_t_offset:  [0.0, 1.4, 0.0]
        device: gpu
        precache: False

    eval:
        type: MipNeRF360
        scene_name: garden
        test_holdout: 24
        img_scale: 0.25
        scale_radius: 3.0
        cam_t_offset:  [0.0, 1.4, 0.0]
        device: gpu
        precache: True

inference:
    to_gpu: True
    render:
        type: [spiral]
        n_cam: [60]
        repeat: [1]
        radius: 3.0
        u_start: 0.0
        v_range: [-0.3, -0.1]
        fps: 5
        surface_render:
            chunk_rays_factor: 1024
            method: sphere_tracing

    volume:
        n_grid: 512
        side: 2.0
        level: 0.0
        grad_dir: ascent
        chunk_pts_factor: 1
        render_mesh:
            backend: pytorch3d

model:
    type: Neus
    obj_bound: # use a sphere bound for sampling. No need to optimize it.
        sphere:
            radius: 1.5
    rays:
        radius_bound: 1.5
        # near: 1.5
        # far: 4.5
        n_sample: 64
        n_importance: 64
        n_iter: 4
        inverse_linear: False
        perturb: True
        add_inf_z: False
        noise_std: 0.0
        white_bkg: False
    params:
        speed_factor: 10              # factor for inv_s = -np.log(init_var)/10 ~= 0.3
        init_var: 0.05                # init var, when it approaches 0, cdf more close
        anneal_end: 50000             # for anneal param, only set during training. please
    chunk_rays: 4096
    chunk_pts: 131072
    geometry:
        W: 256
        D: 8
        skips: [4]
        encoder:
            type: FreqEmbedder
            input_dim: 3
            n_freqs: 10
        W_feat: 256
        geometric_init: True          # use geometric init. need radius_init
        radius_init: 0.75             # geometric init sphere radius
        weight_norm: True
        skip_reduce_output: True
        norm_skip: True
        act_cfg:                      # activation function for dense layer
            type: softplus
            beta: 100
    radiance:
        mode: 'pvnf'
        W: 256
        D: 4
        encoder:
            pts:
                type: FreqEmbedder
                input_dim: 3
                n_freqs: 0            # xyz embed freq, not embedding performed
            view:
                type: FreqEmbedder
                input_dim: 3
                n_freqs: 4
        W_feat_in: 256
        weight_norm: True
    background:
        type: NeRFPP
        bkg_blend: 'rgb'
        rays:
            bounding_radius: 3.0
            n_sample: 32
            n_importance: 64
            perturb: True
            add_inf_z: True         # must set to be True
            noise_std: 0.0
            white_bkg: False
        chunk_rays: 4096
        chunk_pts: 131072
        geometry:
            W: 256
            D: 8
            skips: [4]
            encoder:
                type: FreqEmbedder
                input_dim: 4              # xyz+1/r input channel
                n_freqs: 10
            W_feat: 256
            geometric_init: False
        radiance:
            mode: 'vf'
            W: 128
            D: 1
            encoder:
                view:
                    type: FreqEmbedder
                    input_dim: 3
                    n_freqs: 4
            W_feat_in: 256

loss:
    ImgLoss:
        loss_type: L1
        weight: 1.0
    EikonalLoss:
        key: normal_pts
        weight: 0.1

metric:
    PSNR:

train_metric:
    PSNR:
