name: mipnerf360_garden_multivol

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/mipnerf360_garden_multivol'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/mipnerf360_garden_multivol/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 1024
worker: 4

optim:
    ema:
        decay: 0.95
    lr: 1e-1
    optim_type: adam
    weight_decay: 1e-6
    eps: 1e-15
    lr_scheduler:
        type: MultiStepLR
        lr_gamma: 0.33
        lr_steps: [20000, 30000, 40000, 50000]
    clip_gradients: 0.0
    clip_warmup: 2000
    clip_gradients_warmup: 15.0  # hashgrid sometimes get (-)inf grad

progress:
    start_epoch: -1
    epoch: 50000
    save_time: 1800

    epoch_loss: 100
    iter_loss: 1
    save_progress: True
    epoch_save_progress: 5000
    iter_save_progress: 1

    epoch_save_checkpoint: 10000
    local_progress: False

    epoch_val: 5000
    save_progress_val: False
    max_samples_val: 1

    init_eval: False
    epoch_eval: 10000
    max_samples_eval: 25

dataset:
    train:
        type: MipNeRF360
        scene_name: garden
        img_scale: 0.25
        scale_radius: 3.0
        center_pixel: True
        cam_t_offset: [0.0, 1.4, 0.0]
        device: gpu
        precache: True

    val:
        type: MipNeRF360
        scene_name: garden
        img_scale: 0.25
        center_pixel: True
        scale_radius: 3.0
        cam_t_offset: [0.0, 1.4, 0.0]
        device: gpu
        precache: False

    eval:
        type: MipNeRF360
        scene_name: garden
        img_scale: 0.25
        center_pixel: True
        scale_radius: 3.0
        cam_t_offset: [0.0, 1.4, 0.0]
        device: gpu
        precache: True

inference:
    to_gpu: True
    render:
        type: [spiral]
        n_cam: [60]
        repeat: [1]
        radius: 3.0
        u_start: 0.0
        v_range: [-0.3, -0.1]
        fps: 5
        center_pixel: True


model:
    type: MultiVol                    # direct use it as full model
    basic_volume:
        n_grid: 128
        side: 2.0
        n_cascade: 5
        inclusive: True
    optim:
        epoch_optim: 16
        epoch_optim_warmup: 256
        near_distance: 0.2
        opa_thres: 0.001        # smaller to avoid too much pruning
        ema_optim_decay: 0.95
    rays:
        n_sample: 1024
        n_importance: 0
        cone_angle: 0.00390625
        perturb: True
        add_inf_z: True
        noise_std: 0.0
        white_bkg: True  # sky
    chunk_rays: 32768
    chunk_pts: 1048576
    geometry:
        #type: FusedMLPGeoNet
        use_bias: False
        W: 64
        D: 1
        skips: [ ]
        encoder: # encoder
            type: HashGridEmbedder
            input_dim: 3
            include_input: False
            side: 32.0                # bounding volume for the outside. Should be 2**(n_cas-1)*side
            n_freqs: 0
            n_levels: 16
            n_feat_per_entry: 2
            hashmap_size: 19
            base_res: 16
            max_res: 2048
            backend: tcnn
            dtype: torch.float32  # cast type
        W_feat: 16
        out_act_cfg:
            type: TruncExp
    radiance:
        #type: FusedMLPRadianceNet
        use_bias: False
        mode: 'fv'
        W: 64
        D: 2
        encoder:
            view:
                type: SHEmbedder
                include_input: False
                input_dim: 3
                n_freqs: 4
                backend: tcnn
                dtype: torch.float32  # cast type
        W_feat_in: 16


loss:
    ImgLoss:
        loss_type: Huber
        delta: 0.1
        weight: 3000

metric:
    PSNR:

train_metric:
    PSNR:
