name: hdrreal_flower_hdrnerf

resume: None

debug:
    debug_mode: False
    print_all_grad: False
    get_progress: False

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/hdrreal_flower_hdrnerf'

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/hdrreal_flower_hdrnerf/checkpoints/final.pt.tar'

gpu_ids: -1

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl
    random_seed: None
    slurm: False

batch_size: 2
n_rays: 1024
worker: 4

optim:
    lr: 5e-4
    optim_type: adam
    weight_decay: 0.0
    lr_scheduler:
        type: ExponentialLR
        lr_gamma: 0.1
        lr_steps: [250000]

    clip_gradients: 0.0
    clip_warmup: -1
    clip_gradients_warmup: 0.0

progress:
    start_epoch: -1
    epoch: 200000
    save_time: 1800

    epoch_loss: 100
    iter_loss: 1
    save_progress: False
    epoch_save_progress: 50000
    iter_save_progress: 1

    epoch_val: 50000
    save_progress_val: False
    max_samples_val: 1

    epoch_save_checkpoint: 50000
    local_progress: False

    init_eval: False
    epoch_eval: 50000
    max_samples_eval: 40

dataset:
    train:
        type: HDRReal
        scene_name: flower
        img_scale: 0.25
        ndc_space: True
        device: gpu
        precache: True

    val:
        type: HDRReal
        scene_name: flower
        img_scale: 0.25
        ndc_space: True
        device: gpu
        precache: False

    eval:
        eval_batch_size: 1
        type: HDRReal
        scene_name: flower
        img_scale: 0.25
        ndc_space: True
        device: gpu
        precache: True

model:
    type: HDRNeRF
    rays:
        near: 0.0   # NDC Space
        far: 1.0    # NDC Space
        n_sample: 64
        n_importance: 64  # fair comparison
        inverse_linear: False
        perturb: True
        add_inf_z: True
        noise_std: 0.0
        white_bkg: False
    chunk_rays: 32768
    chunk_pts: 131072
    geometry:
        W: 256
        D: 8
        skips: [4]
        encoder:
            type: FreqEmbedder
            input_dim: 3
            n_freqs: 10
        W_feat: 256
        geometric_init: False
    radiance:
        mode: 'vf'
        W: 128
        D: 1
        encoder:
            view:
                type: FreqEmbedder
                input_dim: 3
                n_freqs: 4
        W_feat_in: 256
        out_act_cfg:
            type: identity  # Do not use sigmoid to hdr dynamic value
    exp_mlps:
        W: 128
        D: 1

loss:
    ImgLoss:
        keys: ['rgb_coarse', 'rgb_fine']
        weight: 1.0
    FixValueLoss:  # unit exp loss
        keys: ['unit_exp_coarse', 'unit_exp_fine']
        fix_value: 0.5
        weight: 0.5

metric:
    PSNR:

train_metric:
    PSNR:
        key: 'rgb_fine'
