dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

data:
    scene_name: buddha
    colmap:
        match_type: 'exhaustive_matcher'        # ['sequential_matcher', 'exhaustive_matcher']
        dense_reconstruct: False                # run for dense reconstruction with point cloud and mesh

dataset:
    train:
        type: Capture
        scene_name: buddha
        img_scale: 0.25              # scale image and intrinsic, < 1 means scale_down
        scale_radius: 3.0            # norm the camera within a sphere with such radius(actual radius litter smaller)
        pc_radius: 2.0               # only keep point cloud in a fix radius ball, scale after cam norm
        precache: False              # precache all the rays at once

model:
    rays:
        bounding_radius: 3.0

inference:
    render:
        type: [spiral]
        n_cam: [60]
        radius: 2.5     # cam distribution is different in front and back
        u_start: 0.7
        v_range: [-0.5, 0.5]

    volume:
        n_grid: 4       # just for visual purpose
        side: 2.5
