dir:
    data_dir: '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

data:
    video_path: '/Users/leoyluo/Desktop/Immerse/data/Capture/hamburger.mp4'
    scene_name: hamburger
    video_downsample: 1             # fps downsample ratio, default 1
    image_downsample: 1             # image rescale downsample ratio, default 1
    colmap:
        match_type: 'sequential_matcher'        # ['sequential_matcher', 'exhaustive_matcher']
        dense_reconstruct: False                # run for dense reconstruction with point cloud and mesh

dataset:
    train:
        type: Capture
        scene_name: hamburger
        skip: 10                     # reduce num of image in sequence
        img_scale: 1.0               # scale image and intrinsic, < 1 means scale_down
        scale_radius: 3.0            # norm the camera within a sphere with such radius(actual radius litter smaller)
        pc_radius: 2.0               # only keep point cloud in a fix radius ball, scale after cam norm
        precache: False              # precache all the rays at once
        augmentation:
            blend_bkg_color:
                bkg_color: [ 1.0, 1.0, 1.0 ]

model:
    rays:
        # bounding_radius: 3.0
        near: 1.5
        far: 4.5

inference:
    render:
        type: [circle]
        n_cam: [20]
        radius: 3.0
        u_start: 0.75
        v_ratio: -0.2

    volume:
        n_grid: 4       # just for visual purpose
        origin: [-0.15, 0, 0.2]
        side: 1.0
