dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

data:
    video_path: '/Users/leoyluo/Desktop/Immerse/data/Capture/joycon.MOV'
    scene_name: joycon
    video_downsample: 1             # fps downsample ratio, default 1
    image_downsample: 1             # image rescale downsample ratio, default 1
    colmap:
        match_type: 'sequential_matcher'        # ['sequential_matcher', 'exhaustive_matcher']
        dense_reconstruct: False                # run for dense reconstruction with point cloud and mesh

dataset:
    train:
        type: Capture
        scene_name: joycon
        skip: 8                      # reduce num of image in sequence
        img_scale: 0.25              # scale image and intrinsic, < 1 means scale_down
        # center_by_view_dirs: True  # just for checking
        scale_radius: 3.0            # norm the camera within a sphere with such radius(actual radius litter smaller)
        pc_radius: 1.0               # only keep point cloud in a fix radius ball, scale after cam norm
        precache: False              # precache all the rays at once

model:
    rays:
        # bounding_radius: 3.0
        near: 1.5
        far: 4.5

inference:
    render:
        type: [swing]
        n_cam: [20]
        radius: 2.0
        u_range: [0.7, 0.9]
        v_range: [-0.12, -0.12]
        n_rot: 1

    volume:
        n_grid: 4       # just for visual purpose
        side: 1.5
