# default config.

name: default

resume: None

debug:
    debug_mode: False               # support debug like checking grad.
    print_all_grad: False           # print all grad for all param in model. Only in debug mode

dir:
    expr_dir: None
    data_dir: '/group/30042/leoyluo/Immerse/data'      # It is the main dataset address containing all dataset

data:
    video_path: '/group/30042/leoyluo/Immerse/data/Capture/qq_tiger.MOV'
    scene_name: qq_tiger
    video_downsample: 15            # fps downsample ratio, default 15 (fps=30, each second 2 image)
    image_downsample: 4             # image rescale downsample ratio, default 4 (each length 1/4)
    colmap:
        match_type: 'sequential_matcher'        # ['sequential_matcher', 'exhaustive_matcher']
        dense_reconstruct: False                # run for dense reconstruction with point cloud and mesh

gpu_ids: -1                         # -1 is cpu, otherwise use list of gpus

dist:
    local_rank: 0
    rank: 0
    world_size: 1
    distributed_backend: nccl       # nccl/mpi
    random_seed: None               # None will not require reproducibility, run benchmark to be faster
    slurm: False                    # use slurm for management

batch_size: 2                       # actually do not use it in training
n_rays: 4096                        # n_rays for each training batch
worker: 4

optim:
    lr: 5e-4
    optim_type: adam                # [adam, sgd, lbfgs, rmsprop]
    weight_decay: 0.0
    maxiters: 5                     # for lbfgs only
    lr_scheduler:
        type: ExponentialLR         # [MultiStepLR, ExponentialLR, PolyLR, CosineAnnealingLR]
        lr_gamma: 0.1               # for ExponentialLR, MultiStepLR, PolyLR
        lr_steps: [200000]          # for ExponentialLR(Use first), MultiStepLR(Use all), PolyLR(Use all)
        tmax: 20                    # for CosineAnnealingLR

    clip_gradients: 0.0             # grad clipping set for init
    clip_warmup: -1                 # warmup epoches. -1 mean not change after warmup
    clip_gradients_warmup: 0.0      # grad cliping after warmup period. Can be smaller incase explode

progress:
    start_epoch: -1                 # -1: resume; 0: finetune. Only for resume mode
    epoch: 300000                   # Num of epoch for training
    save_time: 1800                 # save model after this time(in second). By default 30min

    epoch_loss: 10                  # Num of epoch to display loss
    iter_loss: 1                    # Num of iteration to display loss
    save_progress: False            # Whether to save progress during training
    epoch_save_progress: 100        # Num of epoch for saving progress
    iter_save_progress: 10          # Num of iteration for saving progress

    epoch_val: 1000                  # Num of epoch for validation. -1 means not validation
    save_progress_val: True         # Whether to save progress during validation
    max_samples_val: 1              # Max num of sample to write into image in valid

    epoch_save_checkpoint: 50000    # Num of epoch save checkpoint
    local_progress: False           # When local progress, will write to local files. Otherwise to tensorboard only

    init_eval: False                # Whether to eval the model at first epoch
    epoch_eval: 50000               # Num of epoch eval model on test set. -1 means no evaluation
    max_samples_eval: 3             # Max num of sample to write into image in eval

dataset:
    train:
        type: DTU
        scan_id: 65
        img_scale: 1.0              # scale image and intrinsic, < 1 means scale_down
        scale_radius: 3.0           # norm the camera within a sphere with such radius(actual radius litter smaller)
        precache: True              # precache all the rays at once
        augmentation:
            shuffle: True

    val:
        type: DTU
        scan_id: 65
        img_scale: 0.25
        scale_radius: 3.0
        precache: False

    eval:
        eval_batch_size: 1
        eval_max_sample: 3
        type: DTU
        scan_id: 65
        img_scale: 1.0
        scale_radius: 3.0
        precache: True

test:
    render_type: spiral
    n_cam: 20

model:
    type: NeRF
    rays:
        bounding_radius: 3.0          # bounding ray sampling region
        near: 1.0                     # hardcode near zvals
        far: 8.0                     # hardcode far zvals
        n_sample: 64                  # n_sample for zvals sampling
        n_importance: 128             # n_importance for zvals for hierarchical sampling
        inverse_linear: False         # inverse_linear make zvals close to near
        perturb: True                 # perturb zvals interval
        add_inf_z: True               # Add inf zval for ray marching, do not applied for background
        noise_std: 1.0                # noise for sigma in training
    chunk_rays: 32768                 # each chunk to process 1024*32(ray), enough for 32 GB
    chunk_pts: 786432                 # each chunk to progress 4096*192(pts), for model forward
    geometry:
        W: 256                        # linear hidden neuron
        D: 8                          # num of linear, not include final
        skips: [4]                    # pos to add input embedding
        input_ch: 3                   # xyz input channel
        embed_freq: 10                # xyz embed freq
        W_feat: 256                   # extra feature output
        geometric_init: False         # whether to use geometric init. need radius_init
    radiance:
        mode: 'vf'                    # view_dir and feature only
        W: 128                        # linear hidden dim
        D: 1                          # num of linear, not include final
        input_ch_view: 3              # view input channel
        embed_freq_view: 4            # view embed freq
        W_feat_in: 256                # dim for feature from geometry

loss:
    ImgCFLoss:
        weight: 1.0

metric:
    # PSNRCoarse:
    PSNRFine:
