# eval script

name: eval

model_pt: '/group/30042/leoyluo/Immerse/projects/ArcNerf/experiments/dtu_nerf/checkpoints/final.pt.tar'

dir:
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/ArcNerf/results/dtu_nerf'

gpu_ids: -1                   # -1 for cpu, 0/1/2 for gpu. Do not use multiple gpu

worker: 4

dist:
    rank: 0
    local_rank: 0
    world_size: 1

progress:
    max_samples_eval: 3      # Max num of sample to write into image in eval

dataset:
    eval:
        eval_batch_size: 1
        eval_max_sample: 3
        type: DTU
        scan_id: 65
        img_scale: 1.0
        scale_radius: 3.0
        precache: True

model:
    type: NeRF
    rays:
        bounding_radius: 3.0
        near: 1.0
        far: 8.0
        n_sample: 64
        n_importance: 128
        inverse_linear: False
        perturb: True
        add_inf_z: True
        noise_std: 1.0
    chunk_rays: 65536                 # 1024*64, 32GB
    chunk_pts: 786432                 # 4096*192
    geometry:
        W: 256
        D: 8
        skips: [4]
        input_ch: 3
        embed_freq: 10
        W_feat: 256
        geometric_init: False
    radiance:
        mode: 'vf'
        W: 128
        D: 1
        input_ch_view: 3
        embed_freq_view: 4
        W_feat_in: 256

metric:
    PSNRFine:
