# eval script

name: instantngp

model_pt: '/group/30042/leoyluo/Immerse/projects/simplengp/experiments/instantngp/checkpoints/final.pt.tar'

dir:
    data_dir: '/group/30042/leoyluo/Immerse/data'
    eval_dir: '/group/30042/leoyluo/Immerse/projects/simplengp/results/instantngp'

gpu_ids: 0 # only gpu.

dist:
    local_rank: 0
    rank: 0
    world_size: 1

worker: 0

progress:
    max_samples_eval: 25

dataset:
    eval:
        eval_batch_size: 1
        skip: 8
        type: NeRF
        scene_name: lego
        img_scale: 1.0
        center_pixel: True
        precache: False
        device: gpu
        augmentation:
            blend_bkg_color:
                bkg_color: [0.0, 0.0, 0.0]

model:
    type: NGP
    rays:
        n_sample: 1024
        log_max_allowance: 18  # only used for dynamic batch_size, 1 << 18 = 4096*64
    sampler:
        near_distance: 0.2
        cone_angle: 0.0  # const dt sampling
    dense_grid:
        n_grid: 128
        n_cascades: 1    # only need to keep the inner grid
        aabb_scale: 1.0
        aabb_range: [0.0, 1.0]
        epoch_optim: 16
        epoch_optim_warmup: 256
        opa_thres: 0.01
        decay: 0.95
    network:
        n_levels: 16
        n_feat_per_entry: 2
        hashmap_size: 19
        base_res: 16
        max_res: 2048
    renderer:
        early_stop: 1e-4
        bkg_color: [0.0, 0.0, 0.0]
    chunk_rays: 32768   # 4096 * 16
    chunk_pts: 1048576  # 4096 * 256

metric:
    PSNR:
