dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

dataset:
    train:
        type: DTU
        scan_id: 65
        img_scale: 1.0
        scale_radius: 3.0
        align_cam: True     #  dtu 65 need to adjust
        precache: False

model:
    rays:
        bounding_radius: 3.0
        near: 1.0
        # far: 4.0
        n_sample: 64
        n_importance: 128
        inverse_linear: False
        perturb: True
        add_inf_z: True
        noise_std: 1.0

inference:
    render:
        type: [swing]
        n_cam: [30]
        radius: 3.0
        u_range: [0.65, 0.85]
        v_range: [-0.25, 0.25]
        n_rot: 3
        fps: 5

    volume:
        n_grid: 4       # just for visual purpose
        side: 1.5
