dir:
    data_dir:  '/Users/leoyluo/Desktop/Immerse/data'   # It is the main dataset address containing all dataset

dataset:
    train:
        type: TanksAndTemples
        scene_name: Truck
        skip: 8
        img_scale: 1.0
        scale_radius: 3.0
        precache: False

model:
    rays:
        bounding_radius: 3.0

inference:
    render:
        type: [circle]
        n_cam: [20]
        radius: 2.0     # cam distribution is different in front and back
        u_start: 0.0
        v_ratio: 0.0

    volume:
        n_grid: 4       # just for visual purpose
        side: 1.5
